### ISSUE TITLE
为什么设置好了telegram的没有转到电报，请问是否能增加cookie?

### ISSUE THREAD

**Issue by End-Satan** [Privilege-privacy/Weibo-To-Telegram#1]

**Comment by Privilege-privacy** [comment]
是不是在 config.json 文件中的 chat_id 填错了？如果填在私聊 @getmyid_bot 获取的 user_id 就会以对话的方式转发信息，或者把 bot 和 @getmyid_bot 拉进同一个群组随便发一个信息就会获得当前群组的 chat_id，填 chat_id bot就会转发信息到群组。 

暂时并不打算支持 Cookie ，原因是微博的 Cookie 有效期非常的短只有一天的样子得每天更新，只要博主这条微博不是仅对粉丝开放的，都是能转发的。

**Comment by Privilege-privacy** [comment]
> _未提供说明。_

抱歉 现在才看见信息

**Comment by Privilege-privacy** [comment]
另外运行时是需要保留 db 文件夹和 config.json 文件的，就像我 release 发布的一样
