### ISSUE TITLE
微博的链接地址

### ISSUE THREAD

**Issue by coco163** [Privilege-privacy/Weibo-To-Telegram#12]
微博的链接地址转发到tg后变成了文字,无法点击

**Comment by Privilege-privacy** [comment]
附上日志、截图。

**Comment by coco163** [comment]
你好,这个是日志与截图
root@iZj6cghhmi534w9o8q5cmkZ:/www/python/go# ./Weibo-To-Telegram_Linux_x86_64 
2023/09/02 22:15:07 我用夸克网盘分享了「100多套高质量个人简历模板」，点击链接即可保存。打开「夸克APP」，无需下载在线播放视频，畅享原画5倍速，支持电视投屏。链接：网页链接 https://m.weibo.cn/status/NhtrPcdRr?mblogid=NhtrPcdRr&luicode=10000011&lfid=1076032812196624

 
![1693664002971](https://github.com/Privilege-privacy/Weibo-To-Telegram/assets/5829550/4d7e1dcd-9e8e-4829-bb03-bc61d8315a9c)
![WX20230902-221553](https://github.com/Privilege-privacy/Weibo-To-Telegram/assets/5829550/af5b8d73-fa9c-470a-bd95-7e99fbbe0dbe)
![WX20230902-221545](https://github.com/Privilege-privacy/Weibo-To-Telegram/assets/5829550/a2f182f8-1110-4b99-973f-8ba9ea4b857f)
