### ISSUE TITLE
在windows上运行exe文件闪退，打开后隔几秒就退出去了，无法使用

### ISSUE THREAD

**Issue by Tegfe** [Privilege-privacy/Weibo-To-Telegram#13]

**Comment by Privilege-privacy** [comment]
使用 PowerShell 进入二进制下载目录
例如：`cd D:\`

运行二进制查看报错日志
`.\Weibo-To-Telegram_Windows_x86_64.exe`

**Comment by Tegfe** [comment]
> 使用 PowerShell 进入二进制下载目录 例如：`cd D:\`
> 
> 运行二进制查看报错日志 `.\Weibo-To-Telegram_Windows_x86_64.exe`

似乎是代理的原因，但是我电脑复制打开这个群组链接是没问题的，不知道怎么解决

日志：连接 Telegram 失败Post "https://api.telegram.org/bot******:*********/getMe": dial tcp 67.15.129.210:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
