### ISSUE TITLE
希望增加功能

### ISSUE THREAD

**Issue by michchan9527** [Privilege-privacy/Weibo-To-Telegram#6]
希望相片視頻和ios live圖轉mp4 同步保存到電腦

博文配圖合併

**Comment by Privilege-privacy** [comment]
> 希望相片視頻和ios live圖轉mp4 同步保存到電腦
> 
> 博文配圖合併

Live 图片我在安卓客户端和 Web 端下看到的都为视频，有其他特别的地方吗？

博文配图合并为一组发送，后续会以修改配置文件的方式，自己选择是否开启。

"同步保存到電腦" 是指将图片保存在本地？

**Comment by michchan9527** [comment]
> > 希望相片視頻和ios live圖轉mp4 同步保存到電腦
> > 
> > 博文配圖合併
> 
> Live 图片我在安卓客户端和 Web 端下看到的都为视频，有其他特别的地方吗？
> 
> 博文配图合并为一组发送，后续会以修改配置文件的方式，自己选择是否开启。
> 
> "同步保存到電腦" 是指将图片保存在本地？

對，還有希望可以自己調整等待時間。
在電腦上保存live圖會變成jpg格式，並不會保存成mp4格式，自動保存在本地希望live圖可以轉換mp4格式

**Comment by Privilege-privacy** [comment]
> > > 希望相片視頻和ios live圖轉mp4 同步保存到電腦
> > > 博文配圖合併
> > 
> > 
> > Live 图片我在安卓客户端和 Web 端下看到的都为视频，有其他特别的地方吗？
> > 博文配图合并为一组发送，后续会以修改配置文件的方式，自己选择是否开启。
> > "同步保存到電腦" 是指将图片保存在本地？
> 
> 對，還有希望可以自己調整等待時間。 在電腦上保存live圖會變成jpg格式，並不會保存成mp4格式，自動保存在本地希望live圖可以轉換mp4格式

微博自带的 Mov 格式应该大部分播放器都能打开，实在不想外挂一个 FFmpeg 来转换格式了

**Comment by michchan9527** [comment]
主要怕被和諧,第一時間自動保存Live 圖,可以慢慢看
