### ISSUE TITLE
微博图片显示数量问题

### ISSUE THREAD

**Issue by smoothan** [Privilege-privacy/Weibo-To-Telegram#8]
微博目前支持单条微博18张图片的发送，例如 https://weibo.com/1682075684/MfRwTDohV   现在运行时大于9张图片的微博会只显示9张。请问可否支持一下这种多图的微博？

**Comment by Privilege-privacy** [comment]
> 微博目前支持单条微博18张图片的发送，例如 https://weibo.com/1682075684/MfRwTDohV 现在运行时大于9张图片的微博会只显示9张。请问可否支持一下这种多图的微博？

现在可以了，但是在以博文图片合并发送信息时 `MergeMessage` ,会触发 Telegram  单个媒体组图片不能超过 10 张，18 张图会被拆分为两组发送 [ 10, 8 ]

**Comment by smoothan** [comment]
不好意思，刚才用最新的0.1.3版本试了一下，好像还是没有分两组发送，只有前面的9张。
我把SavePicLocal设置为true，可以看到本地是有保存到所有图片的。

**Comment by Privilege-privacy** [comment]
> 不好意思，刚才用最新的0.1.3版本试了一下，好像还是没有分两组发送，只有前面的9张。 我把SavePicLocal设置为true，可以看到本地是有保存到所有图片的。

自动化分发工具分发到旧版本去了。。现在已经删除重新上传了
